# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/data/review.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/data/review.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/data/review.proto\x12\x0f\x62\x34youeat.review\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\treview_id\x18\x02 \x01(\x05\x12\x14\n\x0cstorage_path\x18\x03 \x01(\t\"\xb5\x01\n\x06Review\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rrestaurant_id\x18\x02 \x01(\x05\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\x05\x12.\n\nvisit_date\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x06images\x18\x07 \x03(\x0b\x32\x16.b4youeat.review.Imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.data.review_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGE']._serialized_start=77
  _globals['_IMAGE']._serialized_end=137
  _globals['_REVIEW']._serialized_start=140
  _globals['_REVIEW']._serialized_end=321
# @@protoc_insertion_point(module_scope)
