# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/services/review_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/services/review_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from proto.data import review_pb2 as proto_dot_data_dot_review__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/services/review_service.proto\x12\x08\x62\x34youeat\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17proto/data/review.proto\"\x1e\n\x10GetReviewRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"<\n\x11GetReviewResponse\x12\'\n\x06review\x18\x01 \x01(\x0b\x32\x17.b4youeat.review.Review\"\x8e\x01\n\x13\x43reateReviewRequest\x12\x15\n\rrestaurant_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12.\n\nvisit_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0e\n\x06rating\x18\x05 \x01(\x05\"?\n\x14\x43reateReviewResponse\x12\'\n\x06review\x18\x01 \x01(\x0b\x32\x17.b4youeat.review.Review2\xa4\x01\n\rReviewService\x12M\n\x0c\x43reateReview\x12\x1d.b4youeat.CreateReviewRequest\x1a\x1e.b4youeat.CreateReviewResponse\x12\x44\n\tGetReview\x12\x1a.b4youeat.GetReviewRequest\x1a\x1b.b4youeat.GetReviewResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.services.review_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREVIEWREQUEST']._serialized_start=107
  _globals['_GETREVIEWREQUEST']._serialized_end=137
  _globals['_GETREVIEWRESPONSE']._serialized_start=139
  _globals['_GETREVIEWRESPONSE']._serialized_end=199
  _globals['_CREATEREVIEWREQUEST']._serialized_start=202
  _globals['_CREATEREVIEWREQUEST']._serialized_end=344
  _globals['_CREATEREVIEWRESPONSE']._serialized_start=346
  _globals['_CREATEREVIEWRESPONSE']._serialized_end=409
  _globals['_REVIEWSERVICE']._serialized_start=412
  _globals['_REVIEWSERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
