version: "3.9"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: .
    environment:
      DB_URL: "postgresql+asyncpg://app:secret@db:5432/app"
      PYTHONPATH: /application/b4youeat
    depends_on:
      - db
    ports:
      - "50051:50051"

volumes:
  pgdata: